### ISSUE TITLE
Flow broken due to username/GDPR issue

### ISSUE THREAD

**Issue by matt-canty-dragon** [go-jira/jira#344] opened 2020-05-20 10:42 UTC
I cannot use go-jira at the moment. My flow is to create issues with `jira create` then use `jira take` and `jira in-progress`.

However as I have been getting this error for a few weeks now I have slowly stopped using it.

```
ERROR Invalid Usage: The query parameter 'username' is not supported in GDPR strict mode.
```

https://github.com/go-jira/jira/issues/333#issuecomment-631077242 this issue only goes so far as fixing the create aspect. But once a ticket is created it also cannot be managed beyond that point. 

I think #343 gets part of the way there, but really a complete switch from username for both assignee and reporter is required. I think also that this is probably a change here... https://github.com/go-jira/jira/blob/417568ca2daf474e8e81643a291dd51fc2446d36/jiracmd/assign.go#L64

**Comment by belambic** [comment] 2020-05-25 17:00
I'm having the same issue, `jira take` just doesn't work any more.

**Comment by erik-niehaus** [comment] 2020-05-30 14:42
Same. Jira create is patch-able with #333, but `jira take` is not functional.

**Comment by matt-canty-dragon** [comment] 2020-06-17 14:57
I gave up a little in order to get the functionality back. I use a custom command `work-on` and have used `curl` to hack the assignment to me.

The use of Regex just keeps this command in line with all the other commands by prefixing the project ID if needed.

```yaml
assignee: stub # your profile ID
api-key: stub # your API key

custom-commands:
  - name: work-on
    help: Assigns issue and moves to in-progress
    aliases:
      - wo
    args:
      - name: ISSUE
        help: issue id to work on
        required: true
    script: |-
      ISSUE={{ args.ISSUE }}
      re='^[0-9]+$'
      if [[ $ISSUE =~ $re ]] ; then
        ISSUE=$JIRA_PROJECT-$ISSUE
      fi

      jira in-progress $ISSUE

      curl --request PUT \
        --url https://projectdrgn.atlassian.net/rest/api/3/issue/$ISSUE/assignee \
        --data '{"accountId":"'$JIRA_ASSIGNEE'"}' \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' \
        --user $JIRA_USER':'$JIRA_API_KEY
```

I found the following helpful:

```yaml
custom-commands:
  - name: printenv
    help: Prints environment variables
    script: printenv
```

**Comment by ryan-gerstenkorn-sp** [comment] 2020-07-02 00:12
@matt-canty-dragon

Thanks for this. Put this version together that doesn't hardcode anything and relies on endpoint being set in the config.

```
  - name: work-on
    help: Assigns issue and moves to in-progress
    aliases:
      - wo
    args:
      - name: ISSUE
        help: issue id to work on
        required: true
    script: |-
      set -eu
      jira in-progress {{args.ISSUE}}

      resp="$(
          curl --silent --request GET \
            --url "${JIRA_ENDPOINT}/rest/api/3/myself" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --user "$JIRA_USER"':'"$JIRA_API_TOKEN"
      )"

      account_id="$(echo $resp | jq -r '.accountId')"

      curl --silent --request PUT \
        --url "${JIRA_ENDPOINT}/rest/api/3/issue/{{args.ISSUE}}/assignee" \
        --data '{"accountId":"'"${account_id}"'"}' \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' \
        --user "${JIRA_USER}"':'"${JIRA_API_TOKEN}"
```

**Comment by nyarly** [comment] 2020-07-17 21:43
This should have been fixed by #317 but AFAICT it's still issuing a query with username. Maybe Jira locked their API more since February? @coryb can you comment?

**Comment by avanier** [comment] 2020-07-21 10:49
For reference, I believe we're talking about the query [here](https://github.com/go-jira/jira/blob/master/jiracmd/assign.go#L63-L65), right?

**Comment by nyarly** [comment] 2020-08-12 22:43
I think that's so, yes.

**Comment by nikclayton-dfinity** [comment] 2020-08-17 09:39
Confirmed not fixed in 1.0.23.

**Comment by nikclayton-dfinity** [comment] 2020-08-18 19:16
If I had to guess, the problem with `jira take` is around https://github.com/go-jira/jira/blob/master/jiracmd/take.go#L21-L23 where it uses the `user` value instead of the `accountId` value if the assignee is blank.

https://github.com/go-jira/jira/blob/master/jiracmd/assign.go#L61-L76 has code to do the right thing, so I think the fix is to just delete lines 21-23 from take.go.

**Comment by nikclayton-dfinity** [comment] 2020-08-18 19:43
The error is because this code in `assign.go`:

```
                if opts.Assignee != "" && opts.Assignee != "-1" {
                        users, err := jira.UserSearch(o, globals.Endpoint.Value, &jira.UserSearchOptions{
                                Username: opts.Assignee,
                        })
                        if err != nil {
                                return err
                        }
```

returns an error -- you can't call `jira.UserSearch` with an email address in GDPR strict mode.

**Comment by nikclayton-dfinity** [comment] 2020-08-18 19:47
In https://github.com/go-jira/jira/pull/317#issuecomment-591062732 @coryb wrote:

> Currently, I don't see value in adding an account-id property to the configs, go-jira has to look up users constantly anyway (for assigning to others, adding watchers, setting reporters, etc) so adding an account-id just complicates configuration for little value.

I think you're going to need to do that -- in GDPR strict mode you can't search by e-mail address, the user is going to have to provide an account ID in their config.

Or for commands where the current user is the default you could use the Myself API call https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/#myself to find the authenticated user's accountId value.

**Comment by matt-canty-dragon** [comment] 2020-08-19 09:19
> use the Myself API call

👍  Agreed, this makes the most sense.

**Comment by nikclayton-dfinity** [comment] 2020-09-03 15:48
Are there details on how to update the schemas? I'm assuming there's some process involving `schemas/fetch-schemas.go`, but it's not documented (as far as I can tell)

**Comment by ldelossa** [comment] 2020-09-04 20:02
I just released https://github.com/go-jira/jira/releases/tag/v1.0.24

This should fix these issues. If it does not "@" me and I will re-open this ticket.

**Closed by ldelossa** 2020-09-04 20:02 UTC
