### ISSUE TITLE
Unable to assign users in a cloud instance

### ISSUE THREAD

**Issue by chx** [go-jira/jira#335] opened 2020-04-29 07:46 UTC
I am using the latest version but no matter what I try I am getting the dreaded `ERROR Invalid Usage: The query parameter 'username' is not supported in GDPR strict mode.` answer. Looking at the source code, https://github.com/go-jira/jira/blob/master/jiracmd/assign.go#L63 even though I did specify the long hex string for the username, it still tries to do a username search https://github.com/go-jira/jira/blob/af7a8f45e4b6cafe520dfa611801e14311314dc2/users.go#L30 which is no longer supported. Would it be possible to skip this search if the username starts with a `~` for example?

**Comment by zenspider** [comment] 2020-05-06 22:13
Probable dupe of #333.

**Comment by ldelossa** [comment] 2020-08-28 22:13
fixed in #364

**Closed by ldelossa** 2020-08-28 22:13 UTC
